/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */
/* biome-ignore-all lint: auto-generated */

declare module "sst" {
  export namespace Resource {
    export const Database: {
      database: string
      host: string
      username: string
      password: string
      port: number
    }
  }
}
export {}